#!/usr/bin/env python3
"""Classify ONE isolated-lab route-loss/recovery trace. No HA access, commands or sleeps.

Input: JSONL with {"t": seconds_since_start, "event": name}; generated by an
independent *isolated* test controller/sniffer, not production Z2M logs.
Events: isolated, alternate_path, link_lost, mtorr_on_air, recovered_command,
command_failed, broadcast_busy, owner_reset, identity_changed. An on-air
MTORR must be confirmed by a radio sniffer; host initialization is not enough.
"""
import argparse
import json
from pathlib import Path

LIMIT_SECONDS = 120


def evaluate(events):
    """Return machine-checkable result; no simulated trace proves real RF recovery."""
    if not events:
        return 'NO_TEST_TRACE'
    if any(not isinstance(e.get('t'), (float, int)) or isinstance(e.get('t'), bool)
           or e['t'] < 0 or not isinstance(e.get('event'), str) for e in events):
        return 'INVALID_TRACE'
    times = [e['t'] for e in events]
    if times != sorted(times) or times[-1] > LIMIT_SECONDS:
        return 'OUT_OF_BOUNDS'
    names = [e['event'] for e in events]
    if any(e in names for e in ('owner_reset', 'identity_changed')):
        return 'HARD_FAILURE'
    if 'isolated' not in names or 'alternate_path' not in names:
        return 'NO_ISOLATED_ALTERNATE_PATH'
    if 'broadcast_busy' in names:
        return 'NCP_BROADCAST_ADMISSION_FAILURE'
    if 'link_lost' not in names:
        return 'NO_FAULT_INJECTED'
    loss = times[names.index('link_lost')]
    sent = [e['t'] for e in events if e['event'] == 'mtorr_on_air' and e['t'] > loss]
    if not sent:
        return 'NO_ON_AIR_REFRESH_EVIDENCE'
    recovered = [e['t'] for e in events if e['event'] == 'recovered_command' and e['t'] > sent[0]]
    if not recovered:
        return 'NO_OBSERVED_RECOVERY'
    if any(e['event'] == 'command_failed' and e['t'] > recovered[0] for e in events):
        return 'UNSTABLE_AFTER_RECOVERY'
    return 'ISOLATED_RECOVERY_PASS'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('trace', type=Path, help='JSONL from a separately verified isolated test rig')
    args = parser.parse_args()
    rows = [json.loads(line) for line in args.trace.read_text(encoding='utf-8').splitlines() if line.strip()]
    result = evaluate(rows)
    print(json.dumps({'verdict': result, 'maximum_seconds': LIMIT_SECONDS,
                      'production_actions': 0, 'note': 'No RF proof without a real isolated sniffer/test rig.'}))
    raise SystemExit(0 if result == 'ISOLATED_RECOVERY_PASS' else 2)


if __name__ == '__main__':
    main()
